import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import clientPromise from "../lib/mongodb";
import { Db, InferIdType, MongoClient } from "mongodb";
import { apiGetMain, mainHost } from "../constants/urls";
import { useRouter } from "next/router";
import React, { useState } from "react";
import { NextPage } from "next";
import MainMenu from "../components/MainMenu";

const Home: NextPage<any> = ({ lang, handleChange, content }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainMenu menu={content?.menu} />
      <main className={styles.main}>
        <select value={lang} onChange={(e) => handleChange(e)}>
          <option value="en">enM</option>
          <option value="ua">uaM</option>
          <option value="ru">ruM</option>
        </select>
        <p>ваш выбор: {lang}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};
export default Home;
