import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import clientPromise from "../lib/mongodb";
import { Db, InferIdType, MongoClient } from "mongodb";
import { apiGetMain, mainHost } from "../constants/urls";
import { useRouter } from "next/router";
import React, { ChangeEvent, useContext, useEffect, useState } from "react";
import { NextPage } from "next";
import MainMenu from "../components/MainMenu/MainMenu";
import { IDataLang } from "../interfaces/interfaces";
// import * as Particles from "particles.js";

interface IProp {
  lang: string;
  handleChange: (e: ChangeEvent<HTMLSelectElement>) => void;
  content: IDataLang;
}

const Home: NextPage<IProp> = ({ lang, handleChange, content }) => {
  const [loading, setLoading] = useState(true);
  // const { projects, contacts, resume, startups } = content?.menu || {};

  useEffect(() => {
    if (content) {
      setLoading(false);
    }
  }, [content]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <div>
          <h1>LOADING</h1>
        </div>
      ) : (
        <>
          {/*<div className="well" id="well">*/}
          {/*  <div id="particles-js"></div>*/}
          {/*  <div id="button-top"></div>*/}
          {/*  <div className="panel">*/}
          {/*    <div className="menu">*/}
          {/*      <ul>*/}
          {/*        <li>*/}
          {/*          <a href="next/link" id="projects">*/}
          {/*            <div className="sign">*/}
          {/*              <p>{projects}</p>*/}
          {/*            </div>*/}
          {/*          </a>*/}
          {/*          <a href="next/link" id="hire">*/}
          {/*            <div className="sign">*/}
          {/*              <p>{contacts}</p>*/}
          {/*            </div>*/}
          {/*          </a>*/}
          {/*          <a href="next/link" id="resume">*/}
          {/*            <div className="sign">*/}
          {/*              <p>{resume}</p>*/}
          {/*            </div>*/}
          {/*          </a>*/}
          {/*          <a href="next/link" id="startups">*/}
          {/*            <div className="sign">*/}
          {/*              <p>{startups}</p>*/}
          {/*            </div>*/}
          {/*          </a>*/}
          {/*        </li>*/}
          {/*      </ul>*/}
          {/*    </div>*/}
          {/*  </div>*/}
          {/*</div>*/}
          {/*<Particles />*/}
          <MainMenu menu={content?.menu} />
          <main className={styles.main}>
            <select value={lang} onChange={(e) => handleChange(e)}>
              <option value="en">enM</option>
              <option value="ua">uaM</option>
              <option value="ru">ruM</option>
            </select>
            <p>ваш выбор: {lang}</p>
          </main>
        </>
      )}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};
export default Home;
